### ISSUE TITLE
GitHub Action Failing 404

### ISSUE THREAD

**Issue by BrennonLee** [dagster-io/dagster-cloud-serverless-quickstart#14]
Using this template and replacing the two secrets (`DAGSTER_CLOUD_API_TOKEN` and `ORGANIZATION_ID`) result in the following error when running the deploy GitHub workflow:

```
DagsterCloudHTTPError: 404 Client Error: Not Found for url: 
https://dagster.cloud//prod/graphql: Not Found
Error: No serverless registry information found - your serverless deployment may still be activating
```

Looks like it might be failing for the same reason here as well. Is this on anyone's radar to get fixed? Or does anyone know of a workaround?

**Comment by notrueblood** [comment]
It seems the README is out of date with the GitHub actions. The actions reference `DAGSTER_CLOUD_URL` and not `ORGANIZATION_ID`. We might be able to infer what `DAGSTER_CLOUD_URL` should be from the error. Something like `https://dagster.cloud/your-org-id` or `https://your-ord-id.dagster.cloud/`

Update: The workaround seems to have worked, the README just has to be updated.

**Comment by notrueblood** [comment]
The secret table in the README should be something like:

| Name                      | Description                                                                                                                                                                                     |
| ------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `DAGSTER_CLOUD_API_TOKEN` | An agent token, for more details see [the Dagster Cloud docs](https://docs.dagster.cloud/auth#managing-user-and-agent-tokens).                                                                  |
| `DAGSTER_CLOUD_URL`       | The Dagster Cloud URL of your Dagster Cloud organization. For example, the pied-piper organization may be found at `https://dagster.cloud/pied-piper` or `https://pied-piper.dagster.cloud/`, either of which are valid values. |

**Comment by BrennonLee** [comment]
Wow, thanks @notrueblood! I previously tried what you suggested yesterday but this time I did `https://dagster.cloud/your-org-id` instead of `https://your-ord-id.dagster.cloud/` and it worked 🚀
